// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchImport(arg1) {
  return window['go']['main']['App']['BatchImport'](arg1);
}

export function CleanupOldAuditLogs(arg1) {
  return window['go']['main']['App']['CleanupOldAuditLogs'](arg1);
}

export function CreateAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteHostKey(arg1) {
  return window['go']['main']['App']['DeleteHostKey'](arg1);
}

export function DeployEmailService() {
  return window['go']['main']['App']['DeployEmailService']();
}

export function DetectServerInfo() {
  return window['go']['main']['App']['DetectServerInfo']();
}

export function ExportAuditLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportAuditLogs'](arg1, arg2, arg3, arg4);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAccounts(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAccounts'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllHostKeys() {
  return window['go']['main']['App']['GetAllHostKeys']();
}

export function GetAuditLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetAuditLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAuditStats() {
  return window['go']['main']['App']['GetAuditStats']();
}

export function GetEmailConfig() {
  return window['go']['main']['App']['GetEmailConfig']();
}

export function GetEmailLogs(arg1, arg2) {
  return window['go']['main']['App']['GetEmailLogs'](arg1, arg2);
}

export function GetSMTPProviders() {
  return window['go']['main']['App']['GetSMTPProviders']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemConfig() {
  return window['go']['main']['App']['GetSystemConfig']();
}

export function IsEncryptionMigrated() {
  return window['go']['main']['App']['IsEncryptionMigrated']();
}

export function ManualCheckExpiry() {
  return window['go']['main']['App']['ManualCheckExpiry']();
}

export function MarkAsSold(arg1) {
  return window['go']['main']['App']['MarkAsSold'](arg1);
}

export function MarkAsUnsold(arg1) {
  return window['go']['main']['App']['MarkAsUnsold'](arg1);
}

export function MigrateEncryption() {
  return window['go']['main']['App']['MigrateEncryption']();
}

export function StartEmailService() {
  return window['go']['main']['App']['StartEmailService']();
}

export function StopEmailService() {
  return window['go']['main']['App']['StopEmailService']();
}

export function TestEmailSend() {
  return window['go']['main']['App']['TestEmailSend']();
}

export function TestServerConnection() {
  return window['go']['main']['App']['TestServerConnection']();
}

export function TrustHostKey(arg1) {
  return window['go']['main']['App']['TrustHostKey'](arg1);
}

export function UpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateEmailConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateEmailConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateServerConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateSystemConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateSystemConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}
