// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BatchImport(arg1:Array<Record<string, any>>):Promise<models.BatchImportResult>;

export function CleanupOldAuditLogs(arg1:number):Promise<void>;

export function CreateAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteHostKey(arg1:number):Promise<void>;

export function DeployEmailService():Promise<void>;

export function DetectServerInfo():Promise<models.ServerInfo>;

export function ExportAuditLogs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetAccount(arg1:number):Promise<models.Account>;

export function GetAccounts(arg1:string,arg2:any,arg3:string,arg4:number,arg5:number):Promise<models.PaginatedAccounts>;

export function GetAllHostKeys():Promise<Array<models.HostKey>>;

export function GetAuditLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<models.PaginatedAuditLogs>;

export function GetAuditStats():Promise<Record<string, number>>;

export function GetEmailConfig():Promise<models.EmailConfig>;

export function GetEmailLogs(arg1:number,arg2:number):Promise<models.EmailLogsResult>;

export function GetSMTPProviders():Promise<Array<models.SMTPProvider>>;

export function GetServerConfig():Promise<models.ServerConfig>;

export function GetServiceStatus():Promise<string>;

export function GetStats():Promise<models.AccountStats>;

export function GetSystemConfig():Promise<models.SystemConfig>;

export function IsEncryptionMigrated():Promise<boolean>;

export function ManualCheckExpiry():Promise<number>;

export function MarkAsSold(arg1:number):Promise<void>;

export function MarkAsUnsold(arg1:number):Promise<void>;

export function MigrateEncryption():Promise<void>;

export function StartEmailService():Promise<void>;

export function StopEmailService():Promise<void>;

export function TestEmailSend():Promise<void>;

export function TestServerConnection():Promise<void>;

export function TrustHostKey(arg1:number):Promise<void>;

export function UpdateAccount(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function UpdateEmailConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function UpdateServerConfig(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function UpdateSystemConfig(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;
